### ISSUE TITLE
Regarding the Mel RoFormer models not using CUDA in latest audio-separator version

### ISSUE THREAD

**Issue by HitRoxxx** [nomadkaraoke/python-audio-separator#97] opened 2024-08-12 13:47 UTC
Using audio-separator 0.18.3

**Below is the log Without CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled and it takes 24 seconds to complete**

2024-08-10 17:49:10,691 - INFO - separator - Separator version 0.18.3 instantiating with output_dir: output/01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info, output_format: WAV
2024-08-10 17:49:10,691 - INFO - separator - Operating System: Linux #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2
2024-08-10 17:49:10,693 - INFO - separator - System: Linux Node: kumar Release: 6.5.0-45-generic Machine: x86_64 Proc: x86_64
2024-08-10 17:49:10,693 - INFO - separator - Python Version: 3.10.12
2024-08-10 17:49:10,693 - INFO - separator - PyTorch Version: 2.4.0+cu121
2024-08-10 17:49:10,732 - INFO - separator - FFmpeg installed: ffmpeg version 4.4.2-0ubuntu0.22.04.1+esm4 Copyright (c) 2000-2021 the FFmpeg developers
2024-08-10 17:49:10,733 - INFO - separator - ONNX Runtime CPU package installed with version: 1.18.1
2024-08-10 17:49:10,890 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-08-10 17:49:10,890 - WARNING - separator - CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled
2024-08-10 17:49:10,890 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt...
2024-08-10 17:49:13,983 - INFO - mdxc_separator - MDXC Separator initialisation complete
2024-08-10 17:49:13,983 - INFO - separator - Load model duration: 00:00:03
2024-08-10 17:49:13,983 - INFO - separator - Starting separation process for audio_file_path: input/01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info.mp3
[src/libmpg123/id3.c:process_comment():584] error: No comment text / valid description?
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:22<00:00,  1.05it/s]
2024-08-10 17:49:37,767 - INFO - mdxc_separator - Saving Instrumental stem to 01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info_(Instrumental)_model_mel_band_roformer_ep_3005_sdr_11.wav...
2024-08-10 17:49:38,048 - INFO - mdxc_separator - Saving Vocals stem to 01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info_(Vocals)_model_mel_band_roformer_ep_3005_sdr_11.wav...
2024-08-10 17:49:38,629 - INFO - common_separator - Clearing input audio file paths, sources and stems...
2024-08-10 17:49:38,636 - INFO - separator - Separation duration: 00:00:24

**Below is the log With ONNXruntime has CUDAExecutionProvider available, enabling acceleration and it still takes 24 seconds to complete**

2024-08-10 17:57:09,935 - INFO - separator - Separator version 0.18.3 instantiating with output_dir: output/01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info, output_format: WAV
2024-08-10 17:57:09,935 - INFO - separator - Operating System: Linux #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 15 16:40:02 UTC 2
2024-08-10 17:57:09,937 - INFO - separator - System: Linux Node: kumar Release: 6.5.0-45-generic Machine: x86_64 Proc: x86_64
2024-08-10 17:57:09,937 - INFO - separator - Python Version: 3.10.12
2024-08-10 17:57:09,937 - INFO - separator - PyTorch Version: 2.4.0+cu118
2024-08-10 17:57:09,974 - INFO - separator - FFmpeg installed: ffmpeg version 4.4.2-0ubuntu0.22.04.1+esm4 Copyright (c) 2000-2021 the FFmpeg developers
2024-08-10 17:57:09,975 - INFO - separator - ONNX Runtime GPU package installed with version: 1.18.1
2024-08-10 17:57:10,023 - INFO - separator - CUDA is available in Torch, setting Torch device to CUDA
2024-08-10 17:57:10,023 - INFO - separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
2024-08-10 17:57:10,023 - INFO - separator - Loading model model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt...
2024-08-10 17:57:13,132 - INFO - mdxc_separator - MDXC Separator initialisation complete
2024-08-10 17:57:13,132 - INFO - separator - Load model duration: 00:00:03
2024-08-10 17:57:13,132 - INFO - separator - Starting separation process for audio_file_path: input/01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info.mp3
[src/libmpg123/id3.c:process_comment():584] error: No comment text / valid description?
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:22<00:00,  1.07it/s]
2024-08-10 17:57:36,507 - INFO - mdxc_separator - Saving Instrumental stem to 01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info_(Instrumental)_model_mel_band_roformer_ep_3005_sdr_11.wav...
2024-08-10 17:57:36,943 - INFO - mdxc_separator - Saving Vocals stem to 01_-_KS_-_Kar_Gayi_Chull_DJMaza.Info_(Vocals)_model_mel_band_roformer_ep_3005_sdr_11.wav...
2024-08-10 17:57:37,454 - INFO - common_separator - Clearing input audio file paths, sources and stems...
2024-08-10 17:57:37,464 - INFO - separator - Separation duration: 00:00:24

**Comment by empz** [comment] 2024-08-24 18:06
I think that warning is a false positive, I've seen that sometimes too but it's clearly using the GPU. 24 seconds for a regular song file is definitely using the GPU. Not really sure why that warning shows.

**Comment by HitRoxxx** [comment] 2024-08-25 08:59
I've been testing various audio processing models on my setup, which includes an NVIDIA 3070 Ti and a Ryzen 9 5950X 16-core processor. So far, the GPU-based models handle the same audio in under 10 seconds, with Deezer's Spleeter taking just 3 seconds for 2 stems. I'm also exploring other pull requests to see if any further optimizations come up. I'll keep you posted on any updates.

**Comment by empz** [comment] 2024-08-25 09:23
> I've been testing various audio processing models on my setup, which includes an NVIDIA 3070 Ti and a Ryzen 9 5950X 16-core processor. So far, the GPU-based models handle the same audio in under 10 seconds, with Deezer's Spleeter taking just 3 seconds for 2 stems. I'm also exploring other pull requests to see if any further optimizations come up. I'll keep you posted on any updates.

Are those numbers by using this library? I get much slower separation times. About a minute with the Roformer models with a RTX 3060 (laptop) and a i7-12700H. I'm running it inside WSL so not sure if that adds some overhead. I do see my full GPU usage spiking when performing a separation.

**Comment by empz** [comment] 2024-08-25 10:00
> > I've been testing various audio processing models on my setup, which includes an NVIDIA 3070 Ti and a Ryzen 9 5950X 16-core processor. So far, the GPU-based models handle the same audio in under 10 seconds, with Deezer's Spleeter taking just 3 seconds for 2 stems. I'm also exploring other pull requests to see if any further optimizations come up. I'll keep you posted on any updates.
> 
> Are those numbers by using this library? I get much slower separation times. About a minute with the Roformer models with a RTX 3060 (laptop) and a i7-12700H. I'm running it inside WSL so not sure if that adds some overhead. I do see my full GPU usage spiking when performing a separation.

Oh yes, I've just tried Deezer Spleeter python library and it's extremely fast. But the quality of the stems is not as good as Roformer's.

**Comment by JackismyShephard** [comment] 2024-08-27 20:30
> > I've been testing various audio processing models on my setup, which includes an NVIDIA 3070 Ti and a Ryzen 9 5950X 16-core processor. So far, the GPU-based models handle the same audio in under 10 seconds, with Deezer's Spleeter taking just 3 seconds for 2 stems. I'm also exploring other pull requests to see if any further optimizations come up. I'll keep you posted on any updates.
> 
> Are those numbers by using this library? I get much slower separation times. About a minute with the Roformer models with a RTX 3060 (laptop) and a i7-12700H. I'm running it inside WSL so not sure if that adds some overhead. I do see my full GPU usage spiking when performing a separation.

I was also surprised by the processing time when using this library with Roformer models. I chalked it up to Roformer models being more complex than older models (MDXNet). Still the disparity is quite extreme.

**Comment by beveradb** [comment] 2024-09-15 15:22
Hey folks, sorry for the slow response on this one, I've been a bit overwhelmed with life and work recently so only just getting back on top of my inbox and PRs / open source code maintenance now.

I'm aware of (and appreciate) your PR #74 from issue #73 @jet082, but I was still a bit confused about this one after having had contradictory results when I did my own testing before merging #84 so I knew I needed to do some more thorough testing before taking any more action on this.

I've done some initial testing, see below:

All results are to separate the same input audio file, `please.flac`, a `03:06` modern pop song, using the CLI e.g. `audio-separator -d -m <model> please.flac`

## Separation duration results

### Code currently on `main` (`audio-separator` version `0.19.1`)

Macbook (M3 Max):

- `model_bs_roformer_ep_317_sdr_12.9755.ckpt`: **01:52**

<img width="800" alt="image" src="https://github.com/user-attachments/assets/a965106d-2e21-4e3b-9d39-0ef7dc418040"><br />

- `model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt`: **01:37**

<img width="800" alt="image" src="https://github.com/user-attachments/assets/ca0e389f-7d84-47c0-9215-42a52df807e6"><br />

Runpod with CUDA GPU (1 x RTX 4000 Ada / 16 vCPU 62 GB RAM):

- `model_bs_roformer_ep_317_sdr_12.9755.ckpt`: **00:41**

<img width="800" alt="root@7f1b23d0e9b1  2024-09-15 11-12-31" src="https://github.com/user-attachments/assets/5fa36aa3-efde-4fa1-a7a3-b46741461de8"><br />

- `model_mel_band_roformer_ep_3005_sdr_11.4360.ckpt`: **00:27**

<img width="1528" alt="root@7f1b23d0e9b1  2024-09-15 11-19-31" src="https://github.com/user-attachments/assets/2d71590b-77fe-42c2-8de0-1c4b4a1df32b">


As you can see from the results above:

- On my Macbook, the Apple Silicon GPU is definitely being used to accelerate both the `BS-` and `Mel-` RoFormer models, with inference time under 2 minutes for both models.

- On the Runpod, the Nvidia GPU with CUDA is definitely being used to accelerate both the `BS-` and `Mel-` RoFormer models, with inference time around 30 seconds for both models.

So, I'm really not sure what issues you're still experiencing but I'm confident the current latest `audio-separator` code is working correctly!

I'm going to close the open PR now because I've confirmed the latest code definitely works with CUDA and Apple Silicon for both RoFormer models. I'm happy to help anyone investigate if it still isn't working for you!

**Comment by beveradb** [comment] 2024-09-15 20:24
Closing this issue as resolved for now as I've tested and confirmed CUDA is working for both of the RoFormer models in the latest version of the code.

If anyone is still unable to get CUDA acceleration working with the latest version of `audio-separator`, feel free to comment in here with as many details as you can provide about what you've already tried.
In general, my experience has been that with CUDA most of the people who have struggled to get it working have been using a mismatched version of CUDA libraries with PyTorch or ONNXRuntime or similar, so I encourage folks to pay close attention to that.
You may be able to use my CUDA 12 Dockerfile here too, depending on your system: https://github.com/nomadkaraoke/python-audio-separator/blob/main/Dockerfile.runpod-cuda12 

You're welcome to tag me for support if you've tried everything you can think of and it's still not working - just please try and share as many details as you can about what you're already tried etc. 😄

**Closed by beveradb** 2024-09-15 20:24 UTC
