### ISSUE TITLE
[Feature]: Realtime Decode MDX for Online Karaoke Plugin

### ISSUE THREAD

**Issue by GenzPN** [nomadkaraoke/python-audio-separator#160] opened 2024-11-27 15:01 UTC
### Description

Feature Request:
Support for Realtime Decode MDX (Online Audio Separation)

I came across an inspiring project called [python-audio-separator-live](https://github.com/nnyj/python-audio-separator-live), which provides audio separation in real-time. I believe integrating a similar capability into the project would open up new possibilities, particularly for those of us interested in building applications like online karaoke plugins.

Use Case:
By enabling real-time audio decoding and separation, users could livestream music tracks while isolating vocals and instrumentals on-the-fly. This would be a game-changer for online karaoke setups, allowing seamless performance and playback directly within a live environment.

  --realtime

**Comment by beveradb** [comment] 2024-11-27 15:15
This is a duplicate of #3, closing. 
If someone wants to raise a PR implementing this feature I'd love to test and merge it!

**Closed by beveradb** 2024-11-27 15:15 UTC
Labels: enhancement
